### ISSUE TITLE
Question about the code of baselines

### ISSUE THREAD

**Issue by Tebmer** [composable-models/llm_multiagent_debate#7]
Thanks for your awesome work!

I see that there are only code for your debate, but no code for running the baselines. 

Could you share the code of baselines? In this way, we can reproduce and follow your work better :)

Thanks!

**Comment by yilundu** [comment]
Hi -- you can run the baselines by adjusting the numbers of rounds of debate (to 1 or 2 for self-reflection) and the number of agents (to 1)

**Comment by Tebmer** [comment]
OK, I get it. Thanks for your reply.
